name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

    
      - name: Run on Push
        if: github.event_name == 'push'
        run: echo "This runs only on push"

      - name: Run on Pull Request
        if: github.event_name == 'pull_request'
        run: echo "This runs only on pull request"

      - name: Run Tests
        run: npm run build